--DTABASE: AppFinanceiro

CREATE TABLE USUARIOS
(
    CODIGO SERIAL PRIMARY KEY,
    NOME VARCHAR(30),
    EMAIL VARCHAR(60),
    SENHA VARCHAR(20),
    CPF VARCHAR(15),
    PERMISSAO VARCHAR(5),
    ATIVO BOOLEAN
);

INSERT INTO USUARIOS (NOME, EMAIL, SENHA, CPF, PERMISSAO, ATIVO) VALUES
('Vitor Fraporti', 'vitorfraporti@hotmail.com', '12345', '034.626.290-93', 'USER', true);

INSERT INTO USUARIOS (NOME, EMAIL, SENHA, CPF, PERMISSAO, ATIVO) VALUES
('ADMIN', 'ADMIN', '654321', '123.456.789-09', 'ADMIN', true);

INSERT INTO USUARIOS (NOME, EMAIL, SENHA, CPF, PERMISSAO, ATIVO) VALUES
('Bianca Magro', 'Bianca@gmail', '654321', '123.456.789-09', 'USER', true);

UPDATE USUARIOS SET CODIGO = 0 WHERE CODIGO = 2;

CREATE TABLE GRUPOS
(
    CODIGO SERIAL PRIMARY KEY,
    NOME VARCHAR(40),
    DESCRICAO VARCHAR(100),
    LIDER INTEGER,
    ATIVO BOOLEAN,
    FOREIGN KEY (LIDER) REFERENCES USUARIOS (CODIGO)
);

INSERT INTO GRUPOS (NOME, DESCRICAO, LIDER, ATIVO) 
	VALUES ('Grupo teste', 'Teste para ver se as relações estão corretas', 1, true);

CREATE TABLE USUARIO_GRUPO
(
    CODIGO SERIAL PRIMARY KEY,
    CODIGO_GRUPO INTEGER,
    CODIGO_USUARIO INTEGER,
    FOREIGN KEY (CODIGO_GRUPO) REFERENCES GRUPOS (CODIGO),
    FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIOS (CODIGO)
);
	
INSERT INTO USUARIO_GRUPO(CODIGO_GRUPO, CODIGO_USUARIO)
	VALUES (1, 1);
INSERT INTO USUARIO_GRUPO(CODIGO_GRUPO, CODIGO_USUARIO)
	VALUES (1, 3);

CREATE TABLE DESPESAS
(
    CODIGO SERIAL PRIMARY KEY,
    NOME VARCHAR(20),
    DESCRICAO VARCHAR(100),
    VALOR NUMERIC(10,2),
    DT_CRIACAO VARCHAR(10),
    DT_QUITADA VARCHAR(10),
    ATIVO BOOLEAN
);

INSERT INTO DESPESAS (NOME, DESCRICAO, VALOR, DT_CRIACAO, ATIVO)
    VALUES ('Agua', 'Conta de agua do mes', 44.34, '2023-05-5', true);
INSERT INTO DESPESAS (NOME, DESCRICAO, VALOR, DT_CRIACAO, ATIVO)
    VALUES ('Luz', 'Conta de luz do mes', 84.59, '2023-04-30', true);
INSERT INTO DESPESAS (NOME, DESCRICAO, VALOR, DT_CRIACAO, ATIVO)
    VALUES ('Salgadinho', 'Doritos no peruzzo', 12.90, '2023-05-10', true);

CREATE TABLE USUARIO_DESPESA
(
    CODIGO SERIAL PRIMARY KEY,
    CODIGO_USUARIO INTEGER,
    CODIGO_DESPESA INTEGER,
    FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIOS (CODIGO),
    FOREIGN KEY (CODIGO_DESPESA) REFERENCES DESPESAS (CODIGO)
);

INSERT INTO USUARIO_DESPESA (CODIGO_USUARIO, CODIGO_DESPESA)
    VALUES (1, 3);

CREATE TABLE GRUPO_DESPESA
(
    CODIGO SERIAL PRIMARY KEY,
    CODIGO_GRUPO INTEGER,
    CODIGO_DESPESA INTEGER,
    FOREIGN KEY (CODIGO_GRUPO) REFERENCES GRUPOS (CODIGO),
    FOREIGN KEY (CODIGO_DESPESA) REFERENCES DESPESAS (CODIGO)
);

INSERT INTO GRUPO_DESPESA (CODIGO_GRUPO, CODIGO_DESPESA)
    VALUES (1, 1);
INSERT INTO GRUPO_DESPESA (CODIGO_GRUPO, CODIGO_DESPESA)
    VALUES (1, 2);

CREATE TABLE USUARIO_GRUPO_DESPESA
(
    CODIGO SERIAL PRIMARY KEY,
    CODIGO_USUARIO INTEGER,
    CODIGO_GRUPO INTEGER,
    CODIGO_DESPESA INTEGER,
    VALOR NUMERIC(10,2),
    ATIVO BOOLEAN,
    FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIOS (CODIGO),
    FOREIGN KEY (CODIGO_GRUPO) REFERENCES GRUPOS (CODIGO),
    FOREIGN KEY (CODIGO_DESPESA) REFERENCES DESPESAS (CODIGO)
);

INSERT INTO USUARIO_GRUPO_DESPESA (CODIGO_USUARIO, CODIGO_GRUPO, CODIGO_DESPESA, VALOR, ATIVO)
    VALUES (1, 1, 1, 22.17, true);
INSERT INTO USUARIO_GRUPO_DESPESA (CODIGO_USUARIO, CODIGO_GRUPO, CODIGO_DESPESA, VALOR, ATIVO)
    VALUES (1, 1, 2, 42.29, true);
INSERT INTO USUARIO_GRUPO_DESPESA (CODIGO_USUARIO, CODIGO_GRUPO, CODIGO_DESPESA, VALOR, ATIVO)
    VALUES (3, 1, 1, 22.17, true);
INSERT INTO USUARIO_GRUPO_DESPESA (CODIGO_USUARIO, CODIGO_GRUPO, CODIGO_DESPESA, VALOR, ATIVO)
    VALUES (3, 1, 2, 42.29, true);

create view V_PRTES_DESPESA_GRUPO as
select
d.codigo as CODIGO_DESPESA, 
d.nome as NOME_DESPESA, 
d.descricao as DESCRICAO_DESPESA,
d.DT_CRIACAO as DATA_CRIACAO,
d.valor as VALOR_TOTAL, 
u.nome as NOME_USUARIO, 
x.valor as VALOR_PARTE,
x.ativo as ATIVO
from usuario_grupo_despesa x
join despesas d on d.codigo = x.codigo_despesa
join grupos gp on gp.codigo = x.codigo_grupo
join usuarios u on u.codigo = x.codigo_usuario;